name: Test Framework POC

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint project
        if: always()
        run: yarn lint-pretty

      - name: Run API tests
        if: always()
        run: yarn test-parallel
